### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by larsbrinkhoff** [alanmimms/kl10-microcode#1]
I tried `node gencode` and got this:

```
/home/lars/src/kl10-microcode/gencode.js:13
const {octal} = require('./util');
      ^

SyntaxError: Unexpected token {
```

I don't know JavaScript, but cursory searches seem to say this is valid syntax since at least a few years back.

My node version is v.4.2.6.  Is this too old?

**Comment by larsbrinkhoff** [comment]
Installed node v12 something which runs the files fine.

**Comment by alanmimms** [comment]
Correct in the first try. I used node v12. I'll add that to package.json to
make it clearer. Sorry.
